### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by NielsSensei** [NielsSensei/TreeCompany_TheSpanishInquisition_IP1_Team13_KdG1819#19]
Waarom is de 1 op veel relatie tussen Organisatie & Events verwijderd?

Ik zou dit graag willen bespreken of terug veranderen. Betreft code in Organisatie.cs. Komt uit deze pull request.

https://github.com/NielsSensei/TreeCompany_TheSpanishInquisition_IP1_Team13_KdG1819/pull/14/files

**Comment by edwinkaiyintam** [comment]
Dat is een fout van ons, tijdens het herbekijken van domain hadden David en ik die lijsten initieel verwijderd. Nadat ik aan Sacha en jou daar wat meer over had gevraagd hebben we moeten backtracken daar waar we soortgelijke aanpassingen hadden gemaakt. Tijdens mijn verificatie van de aanpassingen is die fout tussen organisation en event mij ontglipt. Moeilijk overhead te houden.
