### ISSUE TITLE
Image 

### ISSUE THREAD

**Issue by NielsSensei** [NielsSensei/TreeCompany_TheSpanishInquisition_IP1_Team13_KdG1819#20]
Waarom bestaat deze klasse zelfs nog? Het beste is een boolean in Media. Best deze implementatie herzien.

Gevonden onder image.cs bij deze pull request.
https://github.com/NielsSensei/TreeCompany_TheSpanishInquisition_IP1_Team13_KdG1819/pull/14/files

**Comment by edwinkaiyintam** [comment]
@davidmatei @NathanKdG Hebben jullie dit opgelost? Ik herinner me dit niet.

**Comment by NathanKdG** [comment]
Image.cs & Video.cs zijn nodig voor media modulair te houden en good practice.
Kunnen in beide klasses anonieme klasse met `acceptedExtensions` bijhouden.
(.png .jpg .jpeg .gif & .mp4) bv...
