### ISSUE TITLE
Projects

### ISSUE THREAD

**Issue by NielsSensei** [NielsSensei/TreeCompany_TheSpanishInquisition_IP1_Team13_KdG1819#21]
Waarom is het voor een project belangrijk dat hij weet wie de platformowners zijn en daarvan een lijst bijhoudt?

Gevonden in deze pullrequest onder project.cs
https://github.com/NielsSensei/TreeCompany_TheSpanishInquisition_IP1_Team13_KdG1819/pull/14/files

**Comment by edwinkaiyintam** [comment]
Klopt inderdaad niet, die lijn mag weg. Geen idee eerlijk hoe die lijn daar bij is gekomen.
