### ISSUE TITLE
Interactions

### ISSUE THREAD

**Issue by NielsSensei** [NielsSensei/TreeCompany_TheSpanishInquisition_IP1_Team13_KdG1819#22]
Interaction is een irrelevante klasse. In de Db is deze ook verschoven naar Vote.

Gevonden in interaction.cs vanuit deze pull request.

https://github.com/NielsSensei/TreeCompany_TheSpanishInquisition_IP1_Team13_KdG1819/pull/14/files

**Comment by NielsSensei** [comment]
Dit heeft ook betrekking op IoTDevice.cs want daar zit ook een maffe link in die ik niet zo goed begrijp.

**Comment by edwinkaiyintam** [comment]
About 'interaction.cs'
In de (outdated) domeinmodel bestond de klasse 'interaction' nog. Er werd ons niet verteld dat deze klasse deprecated was en dus ook in het domein moest worden geabsorbeerd in klasse 'vote'.

About 'iot_device.cs'
Wat exact is de maffe link?

**Comment by NielsSensei** [comment]
Voor een reden houdt een iotdevice een vote bij en de lijst van interactions (dit laatste wordt ook deprecated) 
![image](https://user-images.githubusercontent.com/44059248/55573728-fd272000-570a-11e9-9a32-330973a71533.png)

**Comment by edwinkaiyintam** [comment]
![image](https://user-images.githubusercontent.com/45334938/55573784-20ea6600-570b-11e9-9f52-0529179ef1c8.png)

Ja, dat hadden we van de (outdated) DCD

**Comment by NielsSensei** [comment]
Aight dan gooi ik het ff weg.
