### ISSUE TITLE
BL layer needs to be lined up with DAL

### ISSUE THREAD

**Issue by XanderVeldeman** [NielsSensei/TreeCompany_TheSpanishInquisition_IP1_Team13_KdG1819#40]
Volgende classes/methoden geven problemen:
- BL/IdeationQuestionManager/getQuestion() (maakt gebruik van Read() )
- BL/IdeationQuestionManager/MakeFeedback() (onbestaande properties)
- BL/IdeationQuestionManager/MakeFeedback() (aangepaste methodes in DAL)
- BL/ModuleManager (maakt gebruik van Read() )
- BL/PlatformManager (platformowner is ge-yeetus't deletus't)
- BL/ProjectManager/getProject() (maakt gebruik van Read() & **1**)
- BL/VoteManager/handleVotingOnFeedBack() (maakt gebruik van Interaction)
- BL/VoteManager/locationCheck() (ReadDevice() )

Kleine reminder: binnen C# schrijf je methoden in **PascalCase**

**Comment by edwinkaiyintam** [comment]
Ik zal me er mee bezighouden.

**Comment by XanderVeldeman** [comment]
Moet daarom nu ni, ik wordt ni gecockblocked

**Comment by NielsSensei** [comment]
See #42 . Thanks @edwinkaiyintam
