### ISSUE TITLE
Time to have some fun in Identity

### ISSUE THREAD

**Issue by NielsSensei** [NielsSensei/TreeCompany_TheSpanishInquisition_IP1_Team13_KdG1819#72]
First thing (Naam wordt leeg gelaten als je met google inlogt):
![image](https://user-images.githubusercontent.com/44059248/57091930-92b5cf80-6d0a-11e9-9a06-2817bbb90124.png)

Second thing (Als je zonder google inlogt en registreert zoekt hij achter onbestaande providers):
![image](https://user-images.githubusercontent.com/44059248/57091970-a9f4bd00-6d0a-11e9-995d-9c8c7d2cd20d.png)

Third thing: Emails van SendGrid komen zeer traag aan (idk of je daar iets aan kan doen of niet)

**Comment by XanderVeldeman** [comment]
Ik zal morgen proberen de form open te trekken waar ge u email adres ingeeft en daar een verplicht veld toe te voegen voor de naam. Mss da ik ook gewoon een naam kan halen uit de claims van google

**Comment by XanderVeldeman** [comment]
Probleem is blijkbaar gewoon dat hij de accountnaam ni kan vinden. Het is dus eigenlijk erger 😄

**Comment by XanderVeldeman** [comment]
Da van de accountnamen is inmiddels opgelost, OAuth is fucked want het wilt telkens terug naar deze URL gaan 
![image](https://user-images.githubusercontent.com/25788097/57127861-00f1a500-6d92-11e9-97de-98bd29e88731.png)
En dus altijd een nieuw account creëren

**Comment by NielsSensei** [comment]
zie #79

**Comment by XanderVeldeman** [comment]
Probleem zit blijkbaar bij de microsoft provider, heeft te maken van het cancellen van het create account form vanuit de provider
