### ISSUE TITLE
Questionnaire aanmaken zonder fases

### ISSUE THREAD

**Issue by XanderVeldeman** [NielsSensei/TreeCompany_TheSpanishInquisition_IP1_Team13_KdG1819#85]
Als je een questionnaire aanmaakt zonder een Phase krijg je volgende error
![image](https://user-images.githubusercontent.com/25788097/57194056-4654d480-6f42-11e9-90a2-862a652b2b02.png)

![image](https://user-images.githubusercontent.com/25788097/57194034-1e657100-6f42-11e9-9316-c48ad1505cdc.png)

Je kan mss een check toevoegen als er geen phases zijn dat je hiervan een message krijgt op de create pagina die dan redirect naar de create phase pagina?

**Comment by NielsSensei** [comment]
zie #65

**Comment by YeetIntoOblivion** [comment]
Das een strak plan

**Comment by NielsSensei** [comment]
zie #138
