### ISSUE TITLE
ClientID & UserSecret

### ISSUE THREAD

**Issue by NathanKdG** [NielsSensei/TreeCompany_TheSpanishInquisition_IP1_Team13_KdG1819#95]
**Master branch** 4d00d827b9573ec5bae5430723df8ab885b00ea5
An issue when deployed on Google Cloud's VM, trying to access https://34.76.133.167/home/index
Apparently due to UserSecrets of Identity stored in JSON files. (According to @XanderVeldeman, myself I have no idea)

Error message and stacktrace found below:
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>      Request starting HTTP/1.1 GET https://34.76.133.167/home/index  
> fail: Microsoft.AspNetCore.Server.Kestrel[13]
>      Connection id "0HLMJ14QE6SC2", Request id "0HLMJ14QE6SC2:00000001": An unhandled exception was thrown by the application.
> System.ArgumentException: The 'ClientId' option must be provided.
> Parameter name: ClientId
>   at Microsoft.AspNetCore.Authentication.OAuth.OAuthOptions.Validate()
>   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationOptions.Validate(String scheme)
>   at Microsoft.AspNetCore.Authentication.AuthenticationHandler'1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
>   at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
>   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
>   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
>   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
>   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication'1 application)
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>      Request finished in 2.5833ms 500

**Comment by XanderVeldeman** [comment]
Issues moogt ge in het Vlaemsch schrijven jongeheer.

En hij vloekt op de clientID die hij zou moeten kunnen ontvangen voor OAuth, waarschijnlijk [dit ](https://github.com/NielsSensei/TreeCompany_TheSpanishInquisition_IP1_Team13_KdG1819/blob/9419d0a7158b6022a88ad8edba12f93976a45048/UI-MVC/Startup.cs#L46-L50) in de startup.cs.
`services.AddAuthentication().AddGoogle(googleOptions =>
            {
                googleOptions.ClientId = Configuration["Authentication:Google:ClientId"];
                googleOptions.ClientSecret = Configuration["Authentication:Google:ClientSecret"];
            }); `

Normaal wordt dit opgediend door de configuration in [`appsettingss.json`](https://github.com/NielsSensei/TreeCompany_TheSpanishInquisition_IP1_Team13_KdG1819/blob/feature/google-cloud/deploy/UI-MVC/appsettings.json), maar dit is enkel mogelijk in development vanwege security reasons.

Anders moet je eens proberen horen voor mensen die als onderzoekstopic deployment hadden? Of proberen de mode te zetten op development, naargelang wat de docent wenst.

**Comment by XanderVeldeman** [comment]
Ge kunt ook zelf [user-secrets](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-2.2&tabs=windows) instellen met:
`dotnet user-secrets <key> <value>`

**Comment by NathanKdG** [comment]
Na het oplossen van #98 is het geen probleem, omdat het met `sudo -H dotnet run` effectief in **development** mode runt.
