### ISSUE TITLE
npm run build FAIL

### ISSUE THREAD

**Issue by NathanKdG** [NielsSensei/TreeCompany_TheSpanishInquisition_IP1_Team13_KdG1819#98]
**Master Branch** 4d00d827b9573ec5bae5430723df8ab885b00ea5
When running `sudo -H dotnet run` in `~/repo/UI-MVC/` it fails on the `npm run build` command. When executing it manually via `sudo -H npm run build` it also fails.
Log file can't be accessed
*Full message below:*

> Hash: ab9161bf12e1b38a7608
> Version: webpack 4.29.6
> Time: 1819ms
> Built at: 2019-05-08 09:09:42
>                     Asset      Size        Chunks             Chunk Names
>     bootstrap_js.entry.js   493 KiB  bootstrap_js  [emitted]  bootstrap_js
> bootstrap_js.entry.js.map   618 KiB  bootstrap_js  [emitted]  bootstrap_js
>     confirmemail.entry.js  4.29 KiB  confirmemail  [emitted]  confirmemail
> confirmemail.entry.js.map  4.18 KiB  confirmemail  [emitted]  confirmemail
>            index.entry.js  3.79 KiB         index  [emitted]  index
>        index.entry.js.map  3.54 KiB         index  [emitted]  index
>         showmenu.entry.js  4.21 KiB      showmenu  [emitted]  showmenu
>     showmenu.entry.js.map  4.08 KiB      showmenu  [emitted]  showmenu
>                  site.css   188 KiB          site  [emitted]  site
>              site.css.map   242 KiB          site  [emitted]  site
>             site.entry.js  20.6 KiB          site  [emitted]  site
>         site.entry.js.map  22.2 KiB          site  [emitted]  site
>       validation.entry.js   349 KiB    validation  [emitted]  validation
>   validation.entry.js.map   448 KiB    validation  [emitted]  validation
> Entrypoint site = site.css site.entry.js site.css.map site.entry.js.map
> Entrypoint bootstrap_js = bootstrap_js.entry.js bootstrap_js.entry.js.map
> Entrypoint validation = validation.entry.js validation.entry.js.map
> Entrypoint index = index.entry.js index.entry.js.map
> Entrypoint showmenu = showmenu.entry.js showmenu.entry.js.map
> Entrypoint confirmemail = confirmemail.entry.js confirmemail.entry.js.map
> **[./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/lib/loader.js!./wwwroot/css/site.scss] 498 bytes {site} [built] [failed] [1 error]**
> [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {bootstrap_js} [built]
> [./wwwroot/css/site.scss] 1.2 KiB {site} [built]
> [./wwwroot/js/bootstrap_js.js] 68 bytes {bootstrap_js} [built]
> [./wwwroot/js/confirmemail.js] 469 bytes {confirmemail} [built]
> [./wwwroot/js/index.js] 1 bytes {index} [built]
> [./wwwroot/js/showmenu.js] 413 bytes {showmenu} [built]
> [./wwwroot/js/site.js] 180 bytes {site} [built]
> [./wwwroot/js/validation.js] 139 bytes {validation} [built]
>     + 9 hidden modules
> **ERROR in ./wwwroot/css/site.scss (./node_modules/css-loader/dist/cjs.js!/node_modules/sass-loader/lib/loader.js!./wwwroot/css/site.scss)
> Module build failed (from ./node_modules/sass-loader/lib/loader.js):
> Error: Cannot find module 'node-sass'
>     at Function.Module._resolveFilename (module.js:548:15)
>     at Function.Module._load (module.js:475:25)
>     at Module.require (module.js:597:17)
>     at require (/home/nathan_gijselings/repo/UI-MVC/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
>     at Object.sassLoader (/home/nathan_gijselings/repo/UI-MVC/node_modules/sass-loader/lib/loader.js:46:72)
>  @ ./wwwroot/css/site.scss 2:14-125
>  @ ./wwwroot/js/site.js**
> Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/bootstrap/dist/css/bootstrap.css:
>     Entrypoint mini-css-extract-plugin = *
>        2 modules
> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! iptsicityofideas@0.1.0 build: `webpack`
> npm ERR! Exit status 2
> npm ERR! 
> npm ERR! Failed at the iptsicityofideas@0.1.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2019-05-08T09_09_42_227Z-debug.log

**Comment by NielsSensei** [comment]
@NathanKdG Dit is een vrij vaak voorkomende error binnen npm. Zo frequent dat @edwinkaiyintam en @NielsSensei ze vandaag nog gehad hebben. Dit fix je best door de package-lock.json en de node-modules eruit te kegelen (die laatste map kan soms ff duren) en opnieuw npm install te doen zodat ie de voorgenoemde files terug aanmaakt.
