### ISSUE TITLE
Duplicate name check is te streng

### ISSUE THREAD

**Issue by XanderVeldeman** [NielsSensei/TreeCompany_TheSpanishInquisition_IP1_Team13_KdG1819#99]
![image](https://user-images.githubusercontent.com/25788097/57390822-7bb92680-71bd-11e9-9579-6377d2956c91.png)

Als er nog maar eenzelfde woord wordt gebruikt wordt er een exception gegooit.

**Comment by NielsSensei** [comment]
Ik en Sacha hebben het al eens besproken van de week. Op bepaalde dingen gaan wij het gewoon weg halen zoals Antwoorden (niemand weet dit van elkaar dus zou dom zijn hierop te checken) QQs , en ideën.
